version: '3.3'

networks:
  sonarqube:
    driver: overlay
  traefik_traefik:
    external: true

secrets:
    sonardbuser:
        external: true
    sonardbpassword:
        external: true
    sonardburl:
        external: true

services:
    sonarqube:
        image: jumo/jumo-sonarqube:latest
        networks:
            - sonarqube
            - traefik_traefik
        secrets:
            - sonardbuser
            - sonardbpassword
            - sonardburl
        deploy:
            replicas: 1
            labels:                           
             - "traefik.backend=sonarqube"
             - "traefik.port=9000"
             - "traefik.frontend.rule=Host:sonarqube.jumo.world"
             - "traefik.docker.network=traefik_traefik"
