version: '3.3'

services:
  web:
    image: "jumo/www-jumo-world:{{ VERSION }}"
    networks:
      - traefik_traefik
    environment:
      - "SECRETLOC=/run/secrets/web-v{{ VERSION }}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    secrets:
      - source: "web-v{{ VERSION }}"
      - source: github_reader_key_base64
    
    deploy:
      placement:
        constraints: [node.role == worker]
      labels:
        traefik.port: 80
        traefik.frontend.rule: "Host:www-dev.internal.staging.jumo.world, www-dev.external.staging.jumo.world, www-dev.jumo.world, www.jumo.world, jumo.world"
        traefik.docker.network: "traefik_traefik"
      update_config:
        parallelism: 1
        delay: 180s
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        
networks:
  traefik_traefik:
    external: true

secrets:
  web-v{{ VERSION }}:
    file: ./www-jumo-world
  github_reader_key_base64:
external: true